
import React from 'react';
import { Route } from 'react-router-dom';

import {
  AnxietyStress,
  InsomniaPage,
  DigestiveIssues,
  AllergiesHayFever,
  HeadachesMigraines,
  SkinConditions,
  ColdFlu,
  JointPainArthritis,
  WomensHealth,
  ChildrensHealth,
  DepressionMood,
  WeightManagement,
  EyeProblems,
  HighBloodPressure,
  DiabetesSupport,
  AsthmaPage,
  EczemaPage,
  FoodAllergiesPage,
  PanicDisorderPage,
  GeneralizedAnxietyPage,
  IBSPage,
  BacterialInfections,
  ViralInfections,
  FungalInfections,
  UrinaryTractInfections,
  SkinInfections,
  EarSinusInfections,
  RecurrentFevers,
  FeverWithChills,
  SeasonalAllergies,
  Teething,
  Acne,
  Diarrhoea,
  Gastritis,
  ChronicRhinitis,
  BreastTenderness,
  FibroidsSupportive,
  GeneralWeakness,
  ConvalescenceRemedies,
  AllergyCare,
  GutHealth,
  HeartHealth,
  ChildCare,
  CancerSupport,
  AnxietyMentalHealth,
  ENTCare,
  EyeCare,
  HairCare,
  ImmuneBoosters,
  InfectionCare,
  LifestyleCare,
  MentalHealth,
  MuscleCare,
  NutritiveCare,
  PainCare,
  ReproductiveCare,
  RespiratoryCare,
  SkinCare,
  SpecialtyCare,
  ToothCare,
  UrologyCare,
  DustAllergy,
  DrugAllergies,
  PetDanderAllergy,
  MoldAllergy,
  LatexAllergy,
  SinusAllergy,
  ChemotherapySideEffects,
  Palpitations
} from './HealthConcernImports';

export const getHealthConcernRoutes = () => [
  // Health Concern Category Routes
  <Route key="gut-health" path="/diseases-conditions/gut-health" element={<GutHealth />} />,
  <Route key="heart-health" path="/diseases-conditions/heart-health" element={<HeartHealth />} />,
  <Route key="child-care" path="/diseases-conditions/child-care" element={<ChildCare />} />,
  <Route key="cancer-support" path="/diseases-conditions/cancer-support" element={<CancerSupport />} />,
  <Route key="ent-care-1" path="/diseases-conditions/ent-care" element={<ENTCare />} />,
  <Route key="ent-care-2" path="/diseases-conditions/ear-nose-throat" element={<ENTCare />} />,
  <Route key="eye-care" path="/diseases-conditions/eye-care" element={<EyeCare />} />,
  <Route key="hair-care" path="/diseases-conditions/hair-care" element={<HairCare />} />,
  <Route key="immune-boosters" path="/diseases-conditions/immune-boosters" element={<ImmuneBoosters />} />,
  <Route key="infection-care-1" path="/diseases-conditions/infection-care" element={<InfectionCare />} />,
  <Route key="infection-care-2" path="/diseases-conditions/infection" element={<InfectionCare />} />,
  <Route key="lifestyle-care-1" path="/diseases-conditions/lifestyle-care" element={<LifestyleCare />} />,
  <Route key="lifestyle-care-2" path="/diseases-conditions/lifestyle" element={<LifestyleCare />} />,
  <Route key="mental-health" path="/diseases-conditions/mental-health" element={<MentalHealth />} />,
  <Route key="muscle-care-1" path="/diseases-conditions/muscle-care" element={<MuscleCare />} />,
  <Route key="muscle-care-2" path="/diseases-conditions/muscle-joint-care" element={<MuscleCare />} />,
  <Route key="nutritive-care-1" path="/diseases-conditions/nutritive-care" element={<NutritiveCare />} />,
  <Route key="nutritive-care-2" path="/diseases-conditions/nutritive" element={<NutritiveCare />} />,
  <Route key="pain-care" path="/diseases-conditions/pain-care" element={<PainCare />} />,
  <Route key="reproductive-care" path="/diseases-conditions/reproductive-care" element={<ReproductiveCare />} />,
  <Route key="respiratory-care" path="/diseases-conditions/respiratory-care" element={<RespiratoryCare />} />,
  <Route key="skin-care" path="/diseases-conditions/skin-care" element={<SkinCare />} />,
  <Route key="specialty-care" path="/diseases-conditions/specialty-care" element={<SpecialtyCare />} />,
  <Route key="tooth-care" path="/diseases-conditions/tooth-care" element={<ToothCare />} />,
  <Route key="urology-care-1" path="/diseases-conditions/urology-care" element={<UrologyCare />} />,
  <Route key="urology-care-2" path="/diseases-conditions/urinary-care" element={<UrologyCare />} />,
  <Route key="womens-health-1" path="/diseases-conditions/womens-health" element={<WomensHealth />} />,
  <Route key="womens-health-2" path="/diseases-conditions/womens-care" element={<WomensHealth />} />,

  // NEW HIERARCHICAL ROUTES - Allergies (moved from allergy-care to allergies)
  <Route key="seasonal-allergies" path="/diseases-conditions/allergies/seasonal-allergies-hay-fever" element={<SeasonalAllergies />} />,
  <Route key="dust-allergy" path="/diseases-conditions/allergies/dust-allergy" element={<DustAllergy />} />,
  <Route key="food-allergies" path="/diseases-conditions/allergies/food-allergies-milk-gluten-nuts" element={<FoodAllergiesPage />} />,
  <Route key="drug-allergies" path="/diseases-conditions/allergies/drug-allergies" element={<DrugAllergies />} />,
  <Route key="skin-allergies" path="/diseases-conditions/allergies/skin-allergies-hives-eczema-urticaria" element={<EczemaPage />} />,
  <Route key="allergic-rhinitis" path="/diseases-conditions/allergies/allergic-rhinitis" element={<AllergiesHayFever />} />,
  <Route key="pet-dander-allergy" path="/diseases-conditions/allergies/pet-dander-allergy" element={<PetDanderAllergy />} />,
  <Route key="mold-allergy" path="/diseases-conditions/allergies/mold-allergy" element={<MoldAllergy />} />,
  <Route key="latex-allergy" path="/diseases-conditions/allergies/latex-allergy" element={<LatexAllergy />} />,
  <Route key="sinus-allergy" path="/diseases-conditions/allergies/sinus-allergy" element={<SinusAllergy />} />,

  // Cancer Routes
  <Route key="chemotherapy-side-effects" path="/diseases-conditions/cancer/chemotherapy-side-effects-nausea-fatigue" element={<ChemotherapySideEffects />} />,
  <Route key="radiation-skin-reactions" path="/diseases-conditions/cancer/radiation-skin-reactions" element={<CancerSupport />} />,
  <Route key="cancer-related-fatigue" path="/diseases-conditions/cancer/cancer-related-fatigue" element={<CancerSupport />} />,
  <Route key="immune-weakness-cancer" path="/diseases-conditions/cancer/immune-weakness-in-cancer-patients" element={<CancerSupport />} />,
  <Route key="loss-of-appetite-cancer" path="/diseases-conditions/cancer/loss-of-appetite" element={<CancerSupport />} />,
  <Route key="mouth-ulcers-cancer" path="/diseases-conditions/cancer/mouth-ulcers-from-cancer-treatment" element={<CancerSupport />} />,
  <Route key="lymphedema-support" path="/diseases-conditions/cancer/lymphedema-support" element={<CancerSupport />} />,
  <Route key="anxiety-sleep-cancer" path="/diseases-conditions/cancer/anxiety-or-sleep-disorders-during-cancer" element={<CancerSupport />} />,

  // Heart Health Routes
  <Route key="high-blood-pressure" path="/diseases-conditions/heart-health/high-blood-pressure-hypertension" element={<HighBloodPressure />} />,
  <Route key="high-cholesterol" path="/diseases-conditions/heart-health/high-cholesterol-hyperlipidemia" element={<HeartHealth />} />,
  <Route key="palpitations" path="/diseases-conditions/heart-health/palpitations" element={<Palpitations />} />,
  <Route key="angina-pectoris" path="/diseases-conditions/heart-health/angina-pectoris-chest-pain" element={<HeartHealth />} />,
  <Route key="poor-circulation" path="/diseases-conditions/heart-health/poor-circulation" element={<HeartHealth />} />,
  <Route key="varicose-veins" path="/diseases-conditions/heart-health/varicose-veins" element={<HeartHealth />} />,
  <Route key="arrhythmias" path="/diseases-conditions/heart-health/arrhythmias-irregular-heartbeat" element={<HeartHealth />} />,
  <Route key="post-heart-attack" path="/diseases-conditions/heart-health/post-heart-attack-recovery-support" element={<HeartHealth />} />,

  // Legacy routes for backward compatibility
  <Route key="anxiety-stress" path="/diseases-conditions/anxiety-stress" element={<AnxietyStress />} />,
  <Route key="insomnia-sleep" path="/diseases-conditions/insomnia-sleep-disorders" element={<InsomniaPage />} />,
  <Route key="digestive-issues" path="/diseases-conditions/digestive-issues" element={<DigestiveIssues />} />,
  <Route key="allergies-hay-fever" path="/diseases-conditions/allergies-hay-fever" element={<AllergiesHayFever />} />,
  <Route key="headaches-migraines" path="/diseases-conditions/headaches-migraines" element={<HeadachesMigraines />} />,
  <Route key="skin-conditions" path="/diseases-conditions/skin-conditions" element={<SkinConditions />} />,
  <Route key="cold-flu" path="/diseases-conditions/cold-flu" element={<ColdFlu />} />,
  <Route key="joint-pain-arthritis" path="/diseases-conditions/joint-pain-arthritis" element={<JointPainArthritis />} />,
  <Route key="childrens-health" path="/diseases-conditions/childrens-health" element={<ChildrensHealth />} />,
  <Route key="depression-mood" path="/diseases-conditions/depression-mood" element={<DepressionMood />} />,
  <Route key="weight-management" path="/diseases-conditions/weight-management" element={<WeightManagement />} />,
  <Route key="eye-problems" path="/diseases-conditions/eye-problems" element={<EyeProblems />} />,
  <Route key="high-blood-pressure-legacy" path="/diseases-conditions/high-blood-pressure" element={<HighBloodPressure />} />,
  <Route key="diabetes-support" path="/diseases-conditions/diabetes-support" element={<DiabetesSupport />} />
];
