import React from 'react';
import { Route } from 'react-router-dom';

import DigestiveIssuesDetailed from '../../pages/health-concerns/gut-health/DigestiveIssuesDetailed';

import {
  AnxietyStress,
  InsomniaPage,
  DigestiveIssues,
  AllergiesHayFever,
  HeadachesMigraines,
  SkinConditions,
  ColdFlu,
  JointPainArthritis,
  WomensHealth,
  ChildrensHealth,
  DepressionMood,
  WeightManagement,
  EyeProblems,
  HighBloodPressure,
  DiabetesSupport,
  AsthmaPage,
  EczemaPage,
  FoodAllergiesPage,
  PanicDisorderPage,
  GeneralizedAnxietyPage,
  IBSPage,
  BacterialInfections,
  ViralInfections,
  FungalInfections,
  UrinaryTractInfections,
  SkinInfections,
  EarSinusInfections,
  RecurrentFevers,
  FeverWithChills,
  SeasonalAllergies,
  Teething,
  Acne,
  Diarrhoea,
  Gastritis,
  ChronicRhinitis,
  BreastTenderness,
  FibroidsSupportive,
  GeneralWeakness,
  ConvalescenceRemedies,
  AllergyCare,
  GutHealth,
  HeartHealth,
  ChildCare,
  CancerSupport,
  AnxietyMentalHealth,
  EyeCare,
  HairCare,
  ImmuneBoosters,
  InfectionCare,
  LifestyleCare,
  MentalHealth,
  MuscleCare,
  NutritiveCare,
  PainCare,
  ReproductiveCare,
  RespiratoryCare,
  SkinCare,
  SpecialtyCare,
  ToothCare,
  UrologyCare,
  DustAllergy,
  DrugAllergies,
  PetDanderAllergy,
  MoldAllergy,
  LatexAllergy,
  SinusAllergy,
  ChemotherapySideEffects,
  Palpitations,
  Tonsillitis,
  SoreThroat,
  NasalPolyps,
  NoseBleedsEpistaxis,
  Tinnitus,
  LossOfVoiceLaryngitis
} from './HealthConcernImports';

// Import category pages
import AllergiesCategoryPage from '../../pages/health-concerns/AllergiesCategoryPage';
import GutHealthCategoryPage from '../../pages/health-concerns/GutHealthCategoryPage';
import HeartHealthCategoryPage from '../../pages/health-concerns/HeartHealthCategoryPage';
import EyeCareCategoryPage from '../../pages/health-concerns/EyeCareCategoryPage';
import ENTCareCategoryPage from '../../pages/health-concerns/ENTCareCategoryPage';
import WomensHealthCategoryPage from '../../pages/health-concerns/WomensHealthCategoryPage';

export const getHealthConcernRoutes = () => [
  // Main Category Routes with new hero section structure
  <Route key="allergies-main" path="/diseases-conditions/allergies" element={<AllergiesCategoryPage />} />,
  <Route key="gut-health-main" path="/diseases-conditions/gut-health" element={<GutHealthCategoryPage />} />,
  
  // Gut Health - Detailed condition pages
  <Route key="digestive-issues-detailed" path="/diseases-conditions/gut-health/digestive-issues" element={<DigestiveIssuesDetailed />} />,
  <Route key="heart-health-main" path="/diseases-conditions/heart-health" element={<HeartHealthCategoryPage />} />,
  <Route key="eye-care-main" path="/diseases-conditions/eye-care" element={<EyeCareCategoryPage />} />,
  <Route key="ent-care-main" path="/diseases-conditions/ent-care" element={<ENTCareCategoryPage />} />,
  <Route key="womens-health-main" path="/diseases-conditions/womens-health" element={<WomensHealthCategoryPage />} />,
  
  // Other category routes (will be updated to new structure later)
  <Route key="child-care" path="/diseases-conditions/child-care" element={<ChildCare />} />,
  <Route key="cancer-support" path="/diseases-conditions/cancer-support" element={<CancerSupport />} />,
  <Route key="hair-care" path="/diseases-conditions/hair-care" element={<HairCare />} />,
  <Route key="immune-boosters" path="/diseases-conditions/immune-boosters" element={<ImmuneBoosters />} />,
  <Route key="infection-care-1" path="/diseases-conditions/infection-care" element={<InfectionCare />} />,
  <Route key="infection-care-2" path="/diseases-conditions/infection" element={<InfectionCare />} />,
  <Route key="lifestyle-care-1" path="/diseases-conditions/lifestyle-care" element={<LifestyleCare />} />,
  <Route key="lifestyle-care-2" path="/diseases-conditions/lifestyle" element={<LifestyleCare />} />,
  <Route key="mental-health" path="/diseases-conditions/mental-health" element={<MentalHealth />} />,
  <Route key="muscle-care-1" path="/diseases-conditions/muscle-care" element={<MuscleCare />} />,
  <Route key="muscle-care-2" path="/diseases-conditions/muscle-joint-care" element={<MuscleCare />} />,
  <Route key="nutritive-care-1" path="/diseases-conditions/nutritive-care" element={<NutritiveCare />} />,
  <Route key="nutritive-care-2" path="/diseases-conditions/nutritive" element={<NutritiveCare />} />,
  <Route key="pain-care" path="/diseases-conditions/pain-care" element={<PainCare />} />,
  <Route key="reproductive-care" path="/diseases-conditions/reproductive-care" element={<ReproductiveCare />} />,
  <Route key="respiratory-care" path="/diseases-conditions/respiratory-care" element={<RespiratoryCare />} />,
  <Route key="skin-care" path="/diseases-conditions/skin-care" element={<SkinCare />} />,
  <Route key="specialty-care" path="/diseases-conditions/specialty-care" element={<SpecialtyCare />} />,
  <Route key="tooth-care" path="/diseases-conditions/tooth-care" element={<ToothCare />} />,
  <Route key="urology-care-1" path="/diseases-conditions/urology-care" element={<UrologyCare />} />,
  <Route key="urology-care-2" path="/diseases-conditions/urinary-care" element={<UrologyCare />} />,
  <Route key="womens-health-2" path="/diseases-conditions/womens-care" element={<WomensHealth />} />,

  // HIERARCHICAL ROUTES - Allergies
  <Route key="seasonal-allergies" path="/diseases-conditions/allergies/seasonal-allergies-hay-fever" element={<SeasonalAllergies />} />,
  <Route key="dust-allergy" path="/diseases-conditions/allergies/dust-allergy" element={<DustAllergy />} />,
  <Route key="food-allergies" path="/diseases-conditions/allergies/food-allergies-milk-gluten-nuts" element={<FoodAllergiesPage />} />,
  <Route key="drug-allergies" path="/diseases-conditions/allergies/drug-allergies" element={<DrugAllergies />} />,
  <Route key="skin-allergies" path="/diseases-conditions/allergies/skin-allergies-hives-eczema-urticaria" element={<EczemaPage />} />,
  <Route key="allergic-rhinitis" path="/diseases-conditions/allergies/allergic-rhinitis" element={<AllergiesHayFever />} />,
  <Route key="pet-dander-allergy" path="/diseases-conditions/allergies/pet-dander-allergy" element={<PetDanderAllergy />} />,
  <Route key="mold-allergy" path="/diseases-conditions/allergies/mold-allergy" element={<MoldAllergy />} />,
  <Route key="latex-allergy" path="/diseases-conditions/allergies/latex-allergy" element={<LatexAllergy />} />,
  <Route key="sinus-allergy" path="/diseases-conditions/allergies/sinus-allergy" element={<SinusAllergy />} />,

  // HIERARCHICAL ROUTES - Gut Health
  <Route key="ibs" path="/diseases-conditions/gut-health/irritable-bowel-syndrome-ibs" element={<IBSPage />} />,
  <Route key="gastritis-gut" path="/diseases-conditions/gut-health/gastritis-stomach-inflammation" element={<Gastritis />} />,
  <Route key="diarrhoea-gut" path="/diseases-conditions/gut-health/diarrhoea-loose-stools" element={<Diarrhoea />} />,
  <Route key="indigestion" path="/diseases-conditions/gut-health/indigestion-dyspepsia" element={<DigestiveIssues />} />,
  <Route key="loss-appetite-gut" path="/diseases-conditions/gut-health/loss-of-appetite" element={<DigestiveIssues />} />,

  // HIERARCHICAL ROUTES - Heart Health
  <Route key="high-blood-pressure" path="/diseases-conditions/heart-health/high-blood-pressure-hypertension" element={<HighBloodPressure />} />,
  <Route key="high-cholesterol" path="/diseases-conditions/heart-health/high-cholesterol-hyperlipidemia" element={<HeartHealth />} />,
  <Route key="palpitations" path="/diseases-conditions/heart-health/palpitations" element={<Palpitations />} />,
  <Route key="angina-pectoris" path="/diseases-conditions/heart-health/angina-pectoris-chest-pain" element={<HeartHealth />} />,
  <Route key="poor-circulation" path="/diseases-conditions/heart-health/poor-circulation" element={<HeartHealth />} />,
  <Route key="varicose-veins" path="/diseases-conditions/heart-health/varicose-veins" element={<HeartHealth />} />,
  <Route key="arrhythmias" path="/diseases-conditions/heart-health/arrhythmias-irregular-heartbeat" element={<HeartHealth />} />,
  <Route key="post-heart-attack" path="/diseases-conditions/heart-health/post-heart-attack-recovery-support" element={<HeartHealth />} />,

  // HIERARCHICAL ROUTES - Eye Care
  <Route key="eye-strain" path="/diseases-conditions/eye-care/eye-strain-digital-fatigue" element={<EyeProblems />} />,
  <Route key="dry-eyes" path="/diseases-conditions/eye-care/dry-eyes" element={<EyeProblems />} />,
  <Route key="conjunctivitis" path="/diseases-conditions/eye-care/conjunctivitis" element={<EyeProblems />} />,
  <Route key="eye-redness" path="/diseases-conditions/eye-care/eye-redness-itching" element={<EyeProblems />} />,
  <Route key="stye-chalazion" path="/diseases-conditions/eye-care/stye-chalazion" element={<EyeProblems />} />,
  <Route key="vision-weakness" path="/diseases-conditions/eye-care/vision-weakness" element={<EyeProblems />} />,
  <Route key="watering-eyes" path="/diseases-conditions/eye-care/watering-eyes" element={<EyeProblems />} />,
  <Route key="light-sensitivity" path="/diseases-conditions/eye-care/light-sensitivity" element={<EyeProblems />} />,

  // HIERARCHICAL ROUTES - ENT Care
  <Route key="chronic-rhinitis-ent" path="/diseases-conditions/ent-care/chronic-rhinitis" element={<ChronicRhinitis />} />,
  <Route key="earache-otitis-media" path="/diseases-conditions/ent-care/earache-otitis-media" element={<EarSinusInfections />} />,
  <Route key="sinusitis-ent" path="/diseases-conditions/ent-care/sinusitis" element={<EarSinusInfections />} />,
  <Route key="tonsillitis-ent" path="/diseases-conditions/ent-care/tonsillitis" element={<Tonsillitis />} />,
  <Route key="sore-throat-ent" path="/diseases-conditions/ent-care/sore-throat" element={<SoreThroat />} />,
  <Route key="nasal-polyps-ent" path="/diseases-conditions/ent-care/nasal-polyps" element={<NasalPolyps />} />,
  <Route key="nosebleeds-ent" path="/diseases-conditions/ent-care/nose-bleeds-epistaxis" element={<NoseBleedsEpistaxis />} />,
  <Route key="tinnitus-ent" path="/diseases-conditions/ent-care/tinnitus" element={<Tinnitus />} />,
  <Route key="voice-loss-ent" path="/diseases-conditions/ent-care/loss-of-voice-laryngitis" element={<LossOfVoiceLaryngitis />} />,

  // HIERARCHICAL ROUTES - Cancer Support
  <Route key="chemotherapy-side-effects" path="/diseases-conditions/cancer-support/chemotherapy-side-effects-nausea-fatigue" element={<ChemotherapySideEffects />} />,
  <Route key="radiation-skin-reactions" path="/diseases-conditions/cancer-support/radiation-skin-reactions" element={<CancerSupport />} />,
  <Route key="cancer-related-fatigue" path="/diseases-conditions/cancer-support/cancer-related-fatigue" element={<CancerSupport />} />,
  <Route key="immune-weakness-cancer" path="/diseases-conditions/cancer-support/immune-weakness-in-cancer-patients" element={<CancerSupport />} />,
  <Route key="loss-of-appetite-cancer" path="/diseases-conditions/cancer-support/loss-of-appetite" element={<CancerSupport />} />,
  <Route key="mouth-ulcers-cancer" path="/diseases-conditions/cancer-support/mouth-ulcers-from-cancer-treatment" element={<CancerSupport />} />,
  <Route key="lymphedema-support" path="/diseases-conditions/cancer-support/lymphedema-support" element={<CancerSupport />} />,
  <Route key="anxiety-sleep-cancer" path="/diseases-conditions/cancer-support/anxiety-or-sleep-disorders-during-cancer" element={<CancerSupport />} />,

  // Legacy routes for backward compatibility
  <Route key="anxiety-stress" path="/diseases-conditions/anxiety-stress" element={<AnxietyStress />} />,
  <Route key="insomnia-sleep" path="/diseases-conditions/insomnia-sleep-disorders" element={<InsomniaPage />} />,
  <Route key="digestive-issues" path="/diseases-conditions/digestive-issues" element={<DigestiveIssues />} />,
  <Route key="allergies-hay-fever" path="/diseases-conditions/allergies-hay-fever" element={<AllergiesHayFever />} />,
  <Route key="headaches-migraines" path="/diseases-conditions/headaches-migraines" element={<HeadachesMigraines />} />,
  <Route key="skin-conditions" path="/diseases-conditions/skin-conditions" element={<SkinConditions />} />,
  <Route key="cold-flu" path="/diseases-conditions/cold-flu" element={<ColdFlu />} />,
  <Route key="joint-pain-arthritis" path="/diseases-conditions/joint-pain-arthritis" element={<JointPainArthritis />} />,
  <Route key="childrens-health" path="/diseases-conditions/childrens-health" element={<ChildrensHealth />} />,
  <Route key="depression-mood" path="/diseases-conditions/depression-mood" element={<DepressionMood />} />,
  <Route key="weight-management" path="/diseases-conditions/weight-management" element={<WeightManagement />} />,
  <Route key="eye-problems" path="/diseases-conditions/eye-problems" element={<EyeProblems />} />,
  <Route key="high-blood-pressure-legacy" path="/diseases-conditions/high-blood-pressure" element={<HighBloodPressure />} />,
  <Route key="diabetes-support" path="/diseases-conditions/diabetes-support" element={<DiabetesSupport />} />
];
